### ISSUE TITLE
2 point temperature calibration

### ISSUE THREAD

**Issue by mehagy** [michelleckelly/mimsy#7]
Michelle, Thank you for clarifying the 99 column issue.  I also have a question about the requirement for 2 temperatures for the standard calibration.  Is that also with newer MIMS?  Our temperature is the same throughout a run on our output.   We are very excited about your program and hope it works for us!

**Comment by michelleckelly** [comment]
Currently, the script is set up to work only with a two-point temperature calibration (this is for a MIMS setup with two water baths, one set at a lower temperature and the other set at a higher temperature - but it sounds like you guys are running just one water bath). I set up the script for two-point because that's what the labs I've worked in so far have been running - an update for one-point temperature calibration has been on my backburner for a looooong time, I just haven't gotten around to it yet.

But! You haven't been the only group to ask about support for a single-temperature setup, so I'm going to prioritize working through that update and pushing it out (I think I'll be able to get that done by the end of the day on Fri Apr 3rd - the calculation process is essentially the same as the two-temperature standard, just needs a few adjustments)

I am excited that you're trying it!! Please let me know if/when future issues arise!! :)

**Comment by michelleckelly** [comment]
Hi mehagy -

So sorry for the delay on this. I've just published package version 0.6.0, which includes the update for single temperature setups as well as a few other tweaks to improve calculation accuracy. 

The update is currently under review by the CRAN team (may take a day or two to approve) - in the meantime version 0.6.0 can be pulled directly from Github using `devtools` (see instructions under Installation on the [Get Started page](https://michelleckelly.github.io/mimsy/articles/mimsy.html))
