### ISSUE TITLE
one-point temp results

### ISSUE THREAD

**Issue by jmurd** [michelleckelly/mimsy#8]
When I run MIMSY using the one-temp standard, only group 1 results are shown in the output. It does appear that the calibration factors and drift correction factors for each group are presented. When using the two-temp standards all group results display fine. Is there something that I am missing in the code to get all group results to display?

**Comment by michelleckelly** [comment]
Hi jmurd - 

This was definitely due to an internal error in the script - an operation that collects the results from all of the groups was located in the wrong spot. The exact same issue was happening with the two-temp results, which was caught and patched in version 0.6.1, but I forgot to check the structure of the one-temp! Thank you for bringing this to my attention!!

The error has now been patched (package version 0.6.2). I'll push this version to CRAN but it may take 24-48 hours for them to approve the update, so in the meantime you should download the development version with `devtools::install_github("michelleckelly/mimsy")` 

Let me know if it's still wonky, or if you find anything else! Thanks again! :)

**Comment by jmurd** [comment]
Michelle,

Thanks for getting to this so quickly! It is working great now. I really appreciate this program. It will save us a ton of time. We are processing several thousand MIMS samples each summer from core incubations held at a constant temp. So a one point temp program saves us from running another set of temp standards. I did notice our N2 and O2 numbers are off just a bit, which I think may be due to slightly different gas saturation calculations. But It looks like we are using the same refs/equations for that. I need to go back and check my calc sheets.

Justin


Justin N. Murdock
Associate Professor of Biology
Tennessee Tech University
Phone: Biology (931) 372-3147
Website: https://sites.tntech.edu/jnmurdock/

**Comment by michelleckelly** [comment]
Justin - No problem - great to hear that it will be useful for your group! I've also been curious about the amount of difference the choice of gas saturation calculation method makes to the final numbers. 

I'm planning to run a small bench experiment once some of our sensors are back from summer deployment (likely this fall or early winter). The idea is to compare O2 from MIMS samples calculated under a couple different gas saturation calculation methods to the "true" dissolved O2 sensor log - I'll host the raw data and results on the package website, too.

Happy MIMS-ing!
